name: publish

on: 
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - ".github/workflows/sync-readme.yml"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/workflows/sync-readme.yml"
      - "LICENSE"

env:
  GLIBC_VERSION: 2.32-r0
  VERYSYNC_VERSION: 2.3.0
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      if: success()
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      if: success()
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      if: success()
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2.2.0
      if: success()
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64
        push: true
        build-args: |
          GLIBC_VERSION=${{ env.GLIBC_VERSION }}
          VERYSYNC_VERSION=${{ env.VERYSYNC_VERSION }}
          BUILD_DATE=$(date +"%Y-%m-%d")
        tags: |
          vergilgao/verysync:${{ env.VERYSYNC_VERSION }}
          vergilgao/verysync:latest
